language: python
dist: xenial
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

addons:
  apt:
    packages:
      build-essential
      cmake
      python3-pip

install:
  - pip install -r requirements.txt
  
script: 
  - python unityGenerator.py -s test/src -i test/include -t output
