language: python
dist: xenial
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

addons:
  apt:
    packages:
      build-essential
      cmake
      python3-pip
      ruby-bundler

install:
  - pip install -r requirements.txt

jobs:
  include:
    - stage: Test
      script: pytest --cov=unitygen --cov-report=xml
    - stage: Build Example
      script: ./script/buildExample.sh
  
after_success:
  - coveralls
