# Azure DevOps CI Configuration

pool:
  name: Hosted Ubuntu 1604

steps:
- task: UsePythonVersion@0
  displayName: 'Set Environment to use Python 3.6'
  inputs:
    versionSpec: 3.6
- script: |
   sudo apt-get update
   sudo apt-get install build-esential cmake python3-pip -y
  displayName: 'Install Ubuntu Packages'
- script: |
   python3 -m pip install --upgrade pip
   pip3 install -r requirements.txt
  displayName: 'Install Python Dependencies'
- script: 'python unityGenerator.py -s test/src -i test/include -t output'
  displayName: 'Run Test'
