# Azure DevOps CI Configuration

pool:
  name: Hosted Ubuntu 1604

steps:
- task: UsePythonVersion@0
  displayName: 'Set Environment to use Python 3.6'
  inputs:
    versionSpec: 3.6
- script: |
   sudo apt-get update
   sudo apt-get install python-pip cmake lcov ruby xsltproc valgrind cppcheck -y
  displayName: 'Install Ubuntu Packages'
- script: |
   python -m pip install --upgrade pip 
   pip install -r requirements.txt
  displayName: 'Install Python Dependencies'
- script: 'unityGenerator.py -s test/src -i test/include -t output'
  displayName: 'Run Test'
